-- ═══════════════════════════════════════════════════════════════════════════════
-- Extended Seed Data — Additional AD&D 2nd Edition PHB Weapons, Armor & Spells
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─── ADDITIONAL WEAPONS ──────────────────────────────────────────────────────

insert into public.weapons (name, damage_sm, damage_l, weapon_type, speed, weight, cost_gp, range_short, range_medium, range_long) values
  ('Handaxt',                '1d6',   '1d4',   'both',   4,  5.0,   1.0,  10, 20, 30),
  ('Wurfaxt',                '1d6',   '1d4',   'ranged', 4,  5.0,   1.0,  10, 20, 30),
  ('Breitschwert',           '2d4',   '1d6+1', 'melee',  5,  4.0,  10.0,  null, null, null),
  ('Bastardschwert',         '1d8',   '1d12',  'melee',  6, 10.0,  25.0,  null, null, null),
  ('Krummsäbel',             '1d8',   '1d8',   'melee',  5,  4.0,  15.0,  null, null, null),
  ('Rapier',                 '1d6+1', '1d8+1', 'melee',  4,  4.0,  15.0,  null, null, null),
  ('Flegel',                 '1d6+1', '2d4',   'melee',  7, 15.0,  15.0,  null, null, null),
  ('Schwerer Flegel',        '1d10',  '2d4',   'melee',  9, 10.0,  15.0,  null, null, null),
  ('Lanze (leicht)',         '1d6',   '1d8',   'melee',  6,  5.0,   6.0,  null, null, null),
  ('Lanze (schwer)',         '1d8+1', '3d6',   'melee',  8, 15.0,  15.0,  null, null, null),
  ('Pike',                   '1d6',   '1d12',  'melee', 13, 12.0,   5.0,  null, null, null),
  ('Dreizack',               '1d6+1', '3d4',   'both',   7,  5.0,  15.0,  10, 20, 30),
  ('Sense',                  '1d6+1', '2d4',   'melee',  8,  7.0,  18.0,  null, null, null),
  ('Sichel',                 '1d4+1', '1d4',   'melee',  4,  3.0,   6.0,  null, null, null),
  ('Knüppel',                '1d6',   '1d3',   'melee',  4,  3.0,   0.0,  null, null, null),
  ('Peitsche',               '1d2',   '1d2',   'melee',  8,  2.0,   1.0,  null, null, null),
  ('Wurfmesser',             '1d3',   '1d2',   'ranged', 2,  0.5,   0.5,  10, 20, 30),
  ('Blasrohr',               '1',     '1',     'ranged', 5,  1.0,   5.0,  10, 20, 30),
  ('Wurfnetz',               '0',     '0',     'ranged',10, 10.0,   5.0,  null, null, null),
  ('Bola',                   '1d3',   '1d2',   'ranged', 8,  2.0,   0.5,  20, 40, 60),
  ('Kompositbogen (kurz)',   '1d6',   '1d6',   'ranged', 6,  2.0,  75.0,  50, 100, 180),
  ('Kompositbogen (lang)',   '1d6',   '1d6',   'ranged', 7,  3.0, 100.0,  70, 140, 210),
  ('Fußangeln',              '1d4',   '1',     'melee',  0,  2.0,   1.0,  null, null, null),
  ('Streitflegel',           '2d4',   '1d4+1', 'melee',  6,  6.0,   8.0,  null, null, null),
  ('Gleve',                  '1d10',  '2d6',   'melee',  8,  8.0,   8.0,  null, null, null),
  ('Guisarme',               '2d4',   '1d8',   'melee',  8,  8.0,   5.0,  null, null, null),
  ('Langspeer',              '1d8',   '1d8+1', 'melee',  8,  8.0,   5.0,  null, null, null),
  ('Nunchaku',               '1d6',   '1d6',   'melee',  3,  3.0,   5.0,  null, null, null),
  ('Wurfstern',              '1d4',   '1d3',   'ranged', 2,  0.1,   1.0,  10, 20, 30),
  ('Zweihändige Streitaxt',  '1d10',  '2d8',   'melee',  9, 10.0,  10.0,  null, null, null);

-- ─── ADDITIONAL ARMOR ────────────────────────────────────────────────────────

insert into public.armor (name, ac, weight, cost_gp, max_movement) values
  ('Gepolsterte Rüstung',       8, 10.0,    4.0, 12),
  ('Fell-/Tierrüstung',         8, 15.0,    3.0, 12),
  ('Bronzeplatte',               4, 45.0,  400.0,  6),
  ('Elfisches Kettenhemd',       5, 15.0, 1000.0, 12),
  ('Großer Schild',              8, 10.0,   15.0, 12),
  ('Buckler',                    9,  3.0,    8.0, 12),
  ('Helmvisier (offen)',        10,  5.0,   10.0, 12),
  ('Helmvisier (geschlossen)',  10, 10.0,   25.0, 12);

-- ─── ADDITIONAL WIZARD SPELLS ────────────────────────────────────────────────

-- ── Wizard Level 1 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Alarm', 1, 'wizard', 'abjuration', '10 Fuß', '4 Stunden + 0,5 Stunden/Stufe', '20 Fuß Würfel', '{"V","S","M"}',
   'Schützt einen Bereich und warnt den Zauberer bei unbefugtem Betreten.'),
  ('Brennende Hände', 1, 'wizard', 'alteration', '0', 'Sofort', '5 Fuß Bogen', '{"V","S"}',
   'Ein Fächer aus Flammen schießt aus den Fingerspitzen. 1d3+2 Schaden/Stufe (max 1d3+20).'),
  ('Person Bezaubern', 1, 'wizard', 'enchantment', '120 Fuß', 'Speziell', '1 Person', '{"V","S"}',
   'Bezaubert eine humanoide Kreatur, die den Zauberer als vertrauenswürdigen Freund betrachtet.'),
  ('Farbspray', 1, 'wizard', 'alteration', '0', 'Sofort', '20 Fuß Kegel', '{"V","S","M"}',
   'Ein Fächer bunter Lichtstrahlen betäubt, blendet oder bewusstlos macht, je nach TW des Ziels.'),
  ('Sprachen Verstehen', 1, 'wizard', 'alteration', 'Berührung', '5 Runden/Stufe', 'Zauberer', '{"V","S","M"}',
   'Ermöglicht das Verstehen unbekannter geschriebener oder gesprochener Sprachen.'),
  ('Magie Entdecken', 1, 'wizard', 'divination', '0', '2 Runden/Stufe', '10x60 Fuß', '{"V","S"}',
   'Der Zauberer erkennt magische Auren in einem Bereich vor sich.'),
  ('Vergrößern', 1, 'wizard', 'alteration', '5 Fuß/Stufe', '5 Runden/Stufe', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Vergrößert eine Kreatur oder ein Objekt um 20% pro Stufe.'),
  ('Federfall', 1, 'wizard', 'alteration', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V"}',
   'Verlangsamt den Fall einer Kreatur auf sichere Geschwindigkeit.'),
  ('Vertrauten Finden', 1, 'wizard', 'conjuration', '1 Meile/Stufe', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Ruft ein magisches Tier als Vertrauten herbei, das dem Zauberer besondere Fähigkeiten verleiht.'),
  ('Freunde', 1, 'wizard', 'enchantment', '0', '1d4 Runden + 1 Runde/Stufe', '60 Fuß Radius', '{"V","S","M"}',
   'Erhöht das Charisma des Zauberers temporär um 2d4 Punkte.'),
  ('Schmieren', 1, 'wizard', 'conjuration', '10 Fuß', '3 Runden + 1 Runde/Stufe', '10x10 Fuß', '{"V","S","M"}',
   'Bedeckt eine Fläche mit rutschiger Substanz. Kreaturen müssen RW schaffen oder fallen.'),
  ('Portal Verschließen', 1, 'wizard', 'alteration', '20 Fuß/Stufe', '1 Runde/Stufe', '20 qm/Stufe', '{"V"}',
   'Verschließt eine Tür oder ein Tor magisch, als wäre es verriegelt.'),
  ('Licht (Magier)', 1, 'wizard', 'alteration', '60 Fuß', '1 Stunde/Stufe', '20 Fuß Radius', '{"V","S"}',
   'Erzeugt einen hellen Lichtschein an einem Punkt oder Objekt.'),
  ('Ausbessern', 1, 'wizard', 'alteration', '30 Fuß', 'Permanent', '1 Objekt', '{"V","S","M"}',
   'Repariert kleine Brüche oder Risse in einem Objekt.'),
  ('Nachricht', 1, 'wizard', 'alteration', '0', '5 Runden/Stufe', 'Speziell', '{"V","S","M"}',
   'Ermöglicht geflüsterte Kommunikation über eine Entfernung.'),
  ('Reittier', 1, 'wizard', 'conjuration', '10 Fuß', '2 Stunden + 1 Stunde/Stufe', 'Speziell', '{"V","S","M"}',
   'Beschwört ein quasi-reales Pferd, das als Reittier dient.'),
  ('Phantasiegebilde', 1, 'wizard', 'illusion', '60 Fuß + 10 Fuß/Stufe', 'Speziell', '400 qm + 100 qm/Stufe', '{"V","S","M"}',
   'Erschafft eine realistische Illusion, die gesehen werden kann.'),
  ('Schutz vor Bösem (Magier)', 1, 'wizard', 'abjuration', 'Berührung', '2 Runden/Stufe', 'Zauberer', '{"V","S","M"}',
   'Schützt vor bösen Kreaturen: +2 auf RW, -2 auf feindliche Angriffe.'),
  ('Magie Lesen', 1, 'wizard', 'divination', '0', '2 Runden/Stufe', 'Speziell', '{"V","S","M"}',
   'Ermöglicht das Lesen magischer Inschriften und Spruchrollen.'),
  ('Spinnenklettern', 1, 'wizard', 'alteration', 'Berührung', '3 Runden + 1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Das Ziel kann wie eine Spinne an Wänden und Decken klettern.'),
  ('Tensers Schwebende Scheibe', 1, 'wizard', 'alteration', '20 Fuß', '3 Runden + 1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erschafft eine schwebende Scheibe, die bis zu 100 Pfund pro Stufe tragen kann.'),
  ('Unsichtbarer Diener', 1, 'wizard', 'conjuration', '0', '1 Stunde + 1 Runde/Stufe', '30 Fuß', '{"V","S","M"}',
   'Erschafft einen unsichtbaren Diener, der einfache Aufgaben erledigt.'),
  ('Nebelwand', 1, 'wizard', 'alteration', '30 Fuß', '2d4 Runden + 1 Runde/Stufe', '20x10x10 Fuß', '{"V","S","M"}',
   'Erzeugt eine dichte Nebelwand, die die Sicht blockiert.'),
  ('Magierzeichen', 1, 'wizard', 'alteration', 'Berührung', 'Permanent', '6 Zoll', '{"V","S","M"}',
   'Hinterlässt ein persönliches Zeichen des Zauberers auf einem Objekt.');

-- ── Wizard Level 2 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Selbst Verändern', 2, 'wizard', 'alteration', '0', '2d6 Runden + 2 Runden/Stufe', 'Zauberer', '{"V","S"}',
   'Verändert das Aussehen des Zauberers in jede humanoide Form ähnlicher Größe.'),
  ('Blindheit', 2, 'wizard', 'illusion', '30 Fuß + 10 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V"}',
   'Blendet das Ziel dauerhaft, wenn der Rettungswurf misslingt.'),
  ('Verschwimmen', 2, 'wizard', 'illusion', '0', '3 Runden + 1 Runde/Stufe', 'Zauberer', '{"V"}',
   'Der Zauberer erscheint verschwommen; Angreifer erleiden -4 auf den Angriffswurf.'),
  ('Dauerlicht', 2, 'wizard', 'alteration', '60 Fuß', 'Permanent', '60 Fuß Radius', '{"V","S","M"}',
   'Erzeugt permanentes Licht an einem Punkt oder Objekt.'),
  ('Dunkelheit 15 Fuß Radius', 2, 'wizard', 'alteration', '10 Fuß/Stufe', '1 Runde/Stufe + 1 Runde', '15 Fuß Radius', '{"V","S"}',
   'Erzeugt magische Dunkelheit, die normales und Infrarotlicht blockiert.'),
  ('Taubheit', 2, 'wizard', 'illusion', '60 Fuß', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Macht das Ziel dauerhaft taub, wenn der Rettungswurf misslingt.'),
  ('Böses Entdecken', 2, 'wizard', 'divination', '0', '5 Runden/Stufe', '10x180 Fuß', '{"V","S"}',
   'Erkennt die Ausstrahlung von Bösem in einem Bereich.'),
  ('ESP', 2, 'wizard', 'divination', '0', '1 Runde/Stufe', '5 Fuß/Stufe (max 90 Fuß)', '{"V","S","M"}',
   'Erkennt die Oberflächengedanken von Kreaturen in Reichweite.'),
  ('Flammenkugel', 2, 'wizard', 'invocation', '10 Fuß', '1 Runde/Stufe', '3 Fuß Radius', '{"V","S","M"}',
   'Erzeugt eine rollende Feuerkugel, die 2d4 Schaden verursacht.'),
  ('Nebelwolke', 2, 'wizard', 'alteration', '10 Fuß', '4 Runden + 1 Runde/Stufe', '40x20x20 Fuß', '{"V","S"}',
   'Erzeugt eine große Nebelwolke, die die Sicht stark einschränkt.'),
  ('Glitzerstaub', 2, 'wizard', 'conjuration', '10 Fuß', 'Speziell', '20 Fuß Würfel', '{"V","S","M"}',
   'Bedeckt Kreaturen mit leuchtendem Staub. Macht Unsichtbare sichtbar und kann blenden.'),
  ('Levitation', 2, 'wizard', 'alteration', '20 Fuß/Stufe', '1 Runde/Stufe', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Lässt eine Kreatur oder ein Objekt auf- oder abwärts schweben.'),
  ('Magischer Mund', 2, 'wizard', 'alteration', '10 Fuß', 'Speziell', '1 Objekt', '{"V","S","M"}',
   'Verzaubert ein Objekt mit einer Nachricht, die bei Auslösung gesprochen wird.'),
  ('Melfs Säurepfeil', 2, 'wizard', 'conjuration', '180 Fuß', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Schießt einen Säurepfeil auf das Ziel. 2d4 Schaden pro Runde für mehrere Runden.'),
  ('Spiegelbild', 2, 'wizard', 'illusion', '0', '3 Runden/Stufe', '6 Fuß Radius', '{"V","S"}',
   'Erzeugt 1d4+1 illusorische Doppelgänger des Zauberers.'),
  ('Irreführung', 2, 'wizard', 'illusion', '30 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Täuscht Ortungszauber und lenkt sie auf ein anderes Ziel um.'),
  ('Pyrotechnik', 2, 'wizard', 'alteration', '120 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Verwandelt ein Feuer in blendendes Feuerwerk oder erstickenden Rauch.'),
  ('Schwächestrahl', 2, 'wizard', 'enchantment', '10 Fuß + 5 Fuß/Stufe', '1 Runde/Stufe', '1 Kreatur', '{"V","S"}',
   'Schwächt das Ziel um 1d4 Stärkepunkte plus 1 pro 2 Stufen.'),
  ('Seiltrick', 2, 'wizard', 'alteration', 'Berührung', '2 Runden/Stufe', 'Speziell', '{"V","S","M"}',
   'Ein Seil steigt senkrecht empor und öffnet einen extradimensionalen Raum.'),
  ('Zertrümmern', 2, 'wizard', 'alteration', '30 Fuß + 10 Fuß/Stufe', 'Sofort', '3 Fuß Radius', '{"V","S","M"}',
   'Zerstört spröde Materialien oder verursacht 1d6 Schaden an Kreaturen.'),
  ('Stinkende Wolke', 2, 'wizard', 'invocation', '30 Fuß', '1 Runde/Stufe', '20 Fuß Würfel', '{"V","S","M"}',
   'Erzeugt eine übelriechende Wolke; Kreaturen darin müssen RW schaffen oder würgen.'),
  ('Netz', 2, 'wizard', 'invocation', '5 Fuß/Stufe', '2 Runden/Stufe', '80 qm', '{"V","S","M"}',
   'Erzeugt klebrige Fäden, die Kreaturen festhalten und Bewegung verhindern.'),
  ('Magierschloss', 2, 'wizard', 'alteration', 'Berührung', 'Permanent', '30 qm/Stufe', '{"V","S"}',
   'Verschließt eine Tür oder Truhe dauerhaft magisch.');

-- ── Wizard Level 3 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Blinzeln', 3, 'wizard', 'alteration', '0', '1 Runde/Stufe', 'Zauberer', '{"V","S"}',
   'Der Zauberer teleportiert sich zufällig in kurzen Abständen und ist schwer zu treffen.'),
  ('Hellsehen', 3, 'wizard', 'divination', 'Unbegrenzt', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Ermöglicht das Sehen eines entfernten, bekannten Ortes.'),
  ('Magie Bannen', 3, 'wizard', 'abjuration', '120 Fuß', 'Sofort', '30 Fuß Würfel', '{"V","S"}',
   'Hebt magische Effekte in einem Bereich auf. Erfolgschance basiert auf Stufenvergleich.'),
  ('Explosive Runen', 3, 'wizard', 'alteration', 'Berührung', 'Speziell', '10 Fuß Radius', '{"V","S"}',
   'Schreibt explodierende Runen auf ein Objekt. 6d4+6 Schaden beim Lesen.'),
  ('Flammenpfeil', 3, 'wizard', 'conjuration', 'Berührung', '1 Runde', 'Speziell', '{"V","S","M"}',
   'Verwandelt normale Pfeile in magische Flammenpfeile mit 1d6 extra Feuerschaden.'),
  ('Fliegen', 3, 'wizard', 'alteration', 'Berührung', '1 Runde/Stufe + 1d6 Runden', 'Zauberer', '{"V","S","M"}',
   'Verleiht dem Ziel die Fähigkeit zu fliegen mit einer Geschwindigkeit von 18.'),
  ('Windstoß', 3, 'wizard', 'alteration', '0', '1 Runde', '10 Fuß x 10 Fuß/Stufe', '{"V","S","M"}',
   'Erzeugt einen starken Windstoß, der Kreaturen zurückdrängt und Feuer löscht.'),
  ('Hast', 3, 'wizard', 'alteration', '60 Fuß', '3 Runden + 1 Runde/Stufe', '40 Fuß Würfel', '{"V","S","M"}',
   'Verdoppelt die Bewegung und Angriffe der betroffenen Kreaturen. Altert sie um 1 Jahr.'),
  ('Person Festhalten', 3, 'wizard', 'enchantment', '120 Fuß', '2 Runden/Stufe', '1-4 Personen', '{"V","S","M"}',
   'Lähmt 1-4 humanoide Kreaturen, die sich nicht mehr bewegen können.'),
  ('Infravision', 3, 'wizard', 'alteration', 'Berührung', '2 Stunden + 1 Stunde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Verleiht dem Ziel die Fähigkeit, Infrarotlicht zu sehen (60 Fuß).'),
  ('Unsichtbarkeit 10 Fuß Radius', 3, 'wizard', 'illusion', 'Berührung', 'Speziell', '10 Fuß Radius', '{"V","S","M"}',
   'Macht alle Kreaturen im 10-Fuß-Radius unsichtbar.'),
  ('Monsterbeschwörung I', 3, 'wizard', 'conjuration', 'Speziell', '2 Runden + 1 Runde/Stufe', '30 Fuß Radius', '{"V","S","M"}',
   'Beschwört 2d4 Monster mit 1 TW, die dem Zauberer gehorchen.'),
  ('Nichterkennung', 3, 'wizard', 'abjuration', 'Berührung', '1 Stunde/Stufe', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Schützt das Ziel vor Ortungszaubern und magischer Beobachtung.'),
  ('Phantomross', 3, 'wizard', 'conjuration', 'Berührung', '1 Stunde/Stufe', 'Speziell', '{"V","S"}',
   'Erschafft ein quasi-reales Pferd aus Schatten mit steigenden Fähigkeiten je Stufe.'),
  ('Schutz vor Bösem 10 Fuß Radius', 3, 'wizard', 'abjuration', 'Berührung', '2 Runden/Stufe', '10 Fuß Radius', '{"V","S","M"}',
   'Wie Schutz vor Bösem, aber schützt alle Kreaturen in 10 Fuß Radius.'),
  ('Schutz vor normalen Geschossen', 3, 'wizard', 'abjuration', 'Berührung', '1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Schützt vor nicht-magischen Fernkampfwaffen wie Pfeilen und Bolzen.'),
  ('Verlangsamen', 3, 'wizard', 'alteration', '90 Fuß + 10 Fuß/Stufe', '3 Runden + 1 Runde/Stufe', '40 Fuß Würfel', '{"V","S","M"}',
   'Halbiert Bewegung und Angriffe der betroffenen Kreaturen.'),
  ('Suggestion', 3, 'wizard', 'enchantment', '30 Fuß', '1 Stunde + 1 Stunde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Pflanzt dem Ziel einen vernünftig klingenden Vorschlag ein, dem es folgt.'),
  ('Sprachen', 3, 'wizard', 'alteration', '0', '1 Runde/Stufe', '60 Fuß Radius', '{"V","M"}',
   'Ermöglicht die Kommunikation in jeder gesprochenen Sprache.'),
  ('Vampirberührung', 3, 'wizard', 'necromancy', '0', 'Sofort', 'Zauberer', '{"V","S"}',
   'Entzieht dem Ziel bei Berührung 1d6 TP pro 2 Stufen und heilt den Zauberer.'),
  ('Wasseratmung', 3, 'wizard', 'alteration', 'Berührung', '1 Stunde/Stufe + 1d4 Stunden', '1 Kreatur', '{"V","S","M"}',
   'Ermöglicht dem Ziel, unter Wasser zu atmen.'),
  ('Windmauer', 3, 'wizard', 'alteration', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erzeugt eine Wand aus starkem Wind, die Geschosse und Gase ablenkt.');

-- ── Wizard Level 4 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Monster Bezaubern', 4, 'wizard', 'enchantment', '60 Fuß', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Wie Person Bezaubern, wirkt aber auf jede lebende Kreatur.'),
  ('Verwirrung', 4, 'wizard', 'enchantment', '120 Fuß', '2 Runden + 1 Runde/Stufe', '60 Fuß Würfel', '{"V","S","M"}',
   'Verwirrt Kreaturen, die zufällig handeln: angreifen, fliehen oder umherwandern.'),
  ('Ansteckung', 4, 'wizard', 'necromancy', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Infiziert das Ziel mit einer schwächenden Krankheit nach Wahl des Zauberers.'),
  ('Beobachtung Erkennen', 4, 'wizard', 'divination', '0', '1d6+1 Runden', '120 Fuß Radius', '{"V","S","M"}',
   'Erkennt magische Beobachtung wie Hellsehen oder Kristallkugeln im Umkreis.'),
  ('Dimensionstür', 4, 'wizard', 'alteration', '0', 'Sofort', 'Zauberer', '{"V"}',
   'Teleportiert den Zauberer sofort bis zu 30 Fuß pro Stufe weit.'),
  ('Emotion', 4, 'wizard', 'enchantment', '10 Fuß/Stufe', 'Speziell', '20 Fuß Würfel', '{"V","S"}',
   'Erzwingt eine Emotion bei betroffenen Kreaturen: Angst, Hoffnungslosigkeit, Mut oder Wut.'),
  ('Verzauberte Waffe', 4, 'wizard', 'alteration', 'Berührung', '5 Runden/Stufe', '1 Waffe', '{"V","S","M"}',
   'Macht eine normale Waffe vorübergehend zu einer magischen +1 Waffe.'),
  ('Evards Schwarze Tentakel', 4, 'wizard', 'conjuration', '30 Fuß', '1 Stunde/Stufe', '30 Fuß Quadrat', '{"V","S","M"}',
   'Schwarze Tentakel greifen Kreaturen im Bereich und verursachen 1d4 Schaden pro Runde.'),
  ('Furcht', 4, 'wizard', 'illusion', '0', 'Speziell', '60 Fuß Kegel', '{"V","S","M"}',
   'Erzeugt einen Kegel der Furcht; betroffene Kreaturen fliehen in Panik.'),
  ('Feuerschild', 4, 'wizard', 'invocation', '0', '2 Runden + 1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Schild aus Flammen oder Kälte umgibt den Zauberer und reflektiert Schadentypen.'),
  ('Feuerfalle', 4, 'wizard', 'invocation', 'Berührung', 'Permanent', '1 Objekt', '{"V","S","M"}',
   'Verzaubert ein Objekt mit einer Feuerfalle. 1d4+Stufe Schaden beim Öffnen.'),
  ('Tollpatschigkeit', 4, 'wizard', 'enchantment', '10 Fuß/Stufe', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Das Ziel stolpert und fällt hin; es kann nicht effektiv handeln.'),
  ('Kleine Globus der Unverwundbarkeit', 4, 'wizard', 'abjuration', '0', '1 Runde/Stufe', '5 Fuß Radius', '{"V","S","M"}',
   'Kugel schützt den Zauberer vor Zaubern der Stufe 1-3.'),
  ('Halluzinatorisches Gelände', 4, 'wizard', 'illusion', '20 Fuß/Stufe', 'Speziell', '10 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Lässt natürliches Gelände wie eine andere Art von Gelände erscheinen.'),
  ('Eissturm', 4, 'wizard', 'invocation', '10 Fuß/Stufe', 'Sofort', '40 Fuß Radius / 20 Fuß Radius', '{"V","S","M"}',
   'Hagelkörner verursachen 3d10 Schaden oder Eisregen behindert Bewegung.'),
  ('Illusorische Wand', 4, 'wizard', 'illusion', '30 Fuß', 'Permanent', '10x10x10 Fuß', '{"V","S","M"}',
   'Erzeugt die Illusion einer Wand, eines Bodens oder einer Decke.'),
  ('Massmorph', 4, 'wizard', 'alteration', '10 Fuß/Stufe', 'Speziell', '10 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Verwandelt eine Gruppe von Kreaturen in Bäume oder Büsche.'),
  ('Monsterbeschwörung II', 4, 'wizard', 'conjuration', 'Speziell', '3 Runden + 1 Runde/Stufe', '40 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d6 Monster mit 2 TW, die dem Zauberer gehorchen.'),
  ('Otilukes Widerstandsfähige Kugel', 4, 'wizard', 'alteration', '20 Fuß', '1 Runde/Stufe', '1 Fuß Durchmesser/Stufe', '{"V","S","M"}',
   'Umschließt eine Kreatur in einer nahezu unzerstörbaren Kraftkugel.'),
  ('Phantastischer Killer', 4, 'wizard', 'illusion', '5 Fuß/Stufe', '1 Runde/Stufe', '1 Kreatur', '{"V","S"}',
   'Erzeugt eine Illusion der schlimmsten Angst des Ziels, die es töten kann.'),
  ('Pflanzenwachstum', 4, 'wizard', 'alteration', '10 Fuß/Stufe', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Lässt Pflanzen in einem Bereich übermäßig wachsen und verwickeln.'),
  ('Andere Verwandeln', 4, 'wizard', 'alteration', '5 Fuß/Stufe', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Verwandelt eine Kreatur dauerhaft in eine andere Kreaturform.'),
  ('Selbst Verwandeln', 4, 'wizard', 'alteration', '0', '2 Runden/Stufe', 'Zauberer', '{"V","S","M"}',
   'Der Zauberer nimmt die Form einer anderen Kreatur an und erhält deren Fähigkeiten.'),
  ('Fluch Brechen (Magier)', 4, 'wizard', 'abjuration', 'Berührung', 'Permanent', 'Speziell', '{"V","S"}',
   'Entfernt einen Fluch von einer Kreatur oder einem Gegenstand.'),
  ('Dichter Nebel', 4, 'wizard', 'alteration', '30 Fuß', '2d4 Runden + 1 Runde/Stufe', '20 Fuß Würfel', '{"V","S","M"}',
   'Erzeugt dichten Nebel, der Bewegung auf 1 Fuß pro Runde verlangsamt.'),
  ('Steinhaut', 4, 'wizard', 'alteration', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Macht die Haut steinhart; absorbiert eine bestimmte Anzahl an Treffern.'),
  ('Feuerwand', 4, 'wizard', 'invocation', '60 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Erzeugt eine undurchdringliche Wand aus Feuer. 2d6+Stufe Schaden beim Durchqueren.'),
  ('Eiswand', 4, 'wizard', 'invocation', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erzeugt eine Wand aus Eis. 10 Fuß Quadrat pro Stufe.'),
  ('Magierauge', 4, 'wizard', 'divination', '0', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erschafft ein unsichtbares magisches Auge, das erkundet und die Sicht überträgt.');

-- ── Wizard Level 5 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Untote Beleben', 5, 'wizard', 'necromancy', '10 Fuß', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Belebt Skelette oder Zombies aus Leichen. 1 Untoter pro Zauberstufe.'),
  ('Abwendung', 5, 'wizard', 'abjuration', 'Berührung', 'Permanent', '1 Objekt', '{"V","S","M"}',
   'Macht ein Objekt abstoßend oder anziehend für eine bestimmte Kreaturart.'),
  ('Bigbys Blockierende Hand', 5, 'wizard', 'invocation', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erzeugt eine magische Hand, die eine Kreatur daran hindert, sich dem Zauberer zu nähern.'),
  ('Chaos', 5, 'wizard', 'enchantment', '5 Fuß/Stufe', '1 Runde/Stufe', '40 Fuß Würfel', '{"V","S","M"}',
   'Betroffene Kreaturen handeln völlig zufällig und unkontrolliert.'),
  ('Todeswolke', 5, 'wizard', 'invocation', '10 Fuß', '1 Runde/Stufe', '40x20x20 Fuß', '{"V","S","M"}',
   'Giftige Wolke, die Kreaturen mit weniger als 4+1 TW sofort tötet.'),
  ('Kältekegel', 5, 'wizard', 'invocation', '0', 'Sofort', '5 Fuß/Stufe Kegel', '{"V","S","M"}',
   'Kegel aus Kälte verursacht 1d4+1 Schaden pro Stufe.'),
  ('Elementar Beschwören', 5, 'wizard', 'conjuration', '60 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Beschwört einen Elementar mit 8, 12 oder 16 TW, der kontrolliert werden muss.'),
  ('Andere Ebene Kontaktieren', 5, 'wizard', 'divination', '0', 'Speziell', 'Zauberer', '{"V"}',
   'Kontaktiert eine höhere Ebene und stellt Ja/Nein-Fragen. Risiko des Wahnsinns.'),
  ('Halbschattenmonster', 5, 'wizard', 'illusion', '30 Fuß', '1 Runde/Stufe', '20 Fuß Würfel', '{"V","S"}',
   'Erzeugt quasi-reale Monster aus Schatten mit 20% Realität pro 2 Stufen.'),
  ('Verbannung (Magier)', 5, 'wizard', 'abjuration', '20 Fuß', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Zwingt eine außerplanare Kreatur auf ihre Heimatebene zurück.'),
  ('Beherrschung', 5, 'wizard', 'enchantment', '10 Fuß/Stufe', 'Speziell', '1 Person', '{"V","S"}',
   'Der Zauberer kann die Handlungen des Ziels vollständig kontrollieren.'),
  ('Traum', 5, 'wizard', 'illusion', 'Unbegrenzt', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Sendet eine Nachricht an eine schlafende Kreatur über beliebige Entfernung.'),
  ('Erweiterung II', 5, 'wizard', 'alteration', '0', 'Speziell', 'Zauberer', '{"V"}',
   'Verdoppelt die Dauer eines Zaubers der Stufe 1-4.'),
  ('Herstellung', 5, 'wizard', 'alteration', '5 Fuß/Stufe', 'Permanent', '3 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Verwandelt Rohmaterial in fertige Gegenstände.'),
  ('Schwachsinn', 5, 'wizard', 'enchantment', '10 Fuß/Stufe', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Reduziert die Intelligenz des Ziels auf 1. Nur durch Heilung aufhebbar.'),
  ('Monster Festhalten', 5, 'wizard', 'enchantment', '5 Fuß/Stufe', '1 Runde/Stufe', '1-4 Kreaturen', '{"V","S","M"}',
   'Lähmt 1-4 Kreaturen beliebiger Art.'),
  ('Leomunds Geheime Truhe', 5, 'wizard', 'alteration', 'Speziell', '60 Tage', 'Speziell', '{"V","S","M"}',
   'Versteckt eine Truhe in der Ätherebene, abrufbar durch eine Miniaturkopie.'),
  ('Magisches Gefäß', 5, 'wizard', 'necromancy', '10 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Der Zauberer überträgt seine Seele in ein Gefäß und kann andere Körper übernehmen.'),
  ('Monsterbeschwörung III', 5, 'wizard', 'conjuration', 'Speziell', '4 Runden + 1 Runde/Stufe', '50 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d4 Monster mit 3 TW, die dem Zauberer gehorchen.'),
  ('Mordenkainens Treuer Hund', 5, 'wizard', 'conjuration', '10 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Beschwört einen unsichtbaren Wächter, der bellt bei Eindringlingen und beißen kann.'),
  ('Durchgang', 5, 'wizard', 'alteration', '30 Fuß', '1 Stunde + 1 Runde/Stufe', '5x8x10 Fuß', '{"V","S","M"}',
   'Öffnet einen Durchgang durch eine Wand aus Holz, Stein oder Erde.'),
  ('Scheingestalt', 5, 'wizard', 'illusion', '10 Fuß/Stufe', '12 Stunden', 'Speziell', '{"V","S"}',
   'Verändert das Aussehen einer Gruppe von Kreaturen illusorisch.'),
  ('Schattentür', 5, 'wizard', 'illusion', '10 Fuß', '1 Runde', 'Speziell', '{"V","S"}',
   'Erzeugt eine illusorische Tür, durch die der Zauberer unsichtbar wird.'),
  ('Schattenmagie', 5, 'wizard', 'illusion', '50 Fuß + 10 Fuß/Stufe', 'Speziell', 'Speziell', '{"V","S"}',
   'Ahmt Invokationszauber der Stufe 1-3 als quasi-reale Schattenversionen nach.'),
  ('Stein Formen', 5, 'wizard', 'alteration', 'Berührung', 'Permanent', '1 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Formt Stein in jede gewünschte Form um.'),
  ('Telekinese', 5, 'wizard', 'alteration', '10 Fuß/Stufe', '2 Runden / Sofort', '25 Pfund/Stufe', '{"V","S"}',
   'Bewegt Objekte oder Kreaturen mit Gedankenkraft.'),
  ('Teleportieren', 5, 'wizard', 'alteration', 'Berührung', 'Sofort', 'Zauberer', '{"V"}',
   'Teleportiert den Zauberer sofort an einen bekannten Ort. Fehlerrisiko je nach Vertrautheit.'),
  ('Fels zu Schlamm', 5, 'wizard', 'alteration', '10 Fuß/Stufe', 'Speziell', '20 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Verwandelt Fels in Schlamm oder umgekehrt.'),
  ('Kraftwand', 5, 'wizard', 'invocation', '30 Fuß', '1 Runde/Stufe', '10 Fuß Quadrat/Stufe', '{"V","S","M"}',
   'Erzeugt eine unzerstörbare, unsichtbare Wand aus reiner Kraft.'),
  ('Eisenwand', 5, 'wizard', 'invocation', '5 Fuß/Stufe', 'Permanent', '15 qm/Stufe', '{"V","S","M"}',
   'Erzeugt eine massive Eisenwand. 0,25 Zoll dick pro Stufe.'),
  ('Steinwand', 5, 'wizard', 'invocation', '5 Fuß/Stufe', 'Permanent', '20 qm/Stufe', '{"V","S","M"}',
   'Erzeugt eine Wand aus solidem Stein. 0,25 Zoll dick pro Stufe.');

-- ── Wizard Level 6 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Antimagische Hülle', 6, 'wizard', 'abjuration', '0', '1 Runde/Stufe', '5 Fuß Radius', '{"V","S"}',
   'Erzeugt eine Sphäre, in der keine Magie wirkt — auch nicht die des Zauberers.'),
  ('Kettenblitz', 6, 'wizard', 'invocation', '40 Fuß + 5 Fuß/Stufe', 'Sofort', 'Speziell', '{"V","S","M"}',
   'Blitz springt von Ziel zu Ziel. Erster Treffer Stufe d6, dann jeweils 1d6 weniger.'),
  ('Kontingenz', 6, 'wizard', 'invocation', '0', '1 Tag/Stufe', 'Zauberer', '{"V","S","M"}',
   'Bindet einen Zauber an eine Bedingung, der dann automatisch ausgelöst wird.'),
  ('Wetter Kontrollieren (Magier)', 6, 'wizard', 'alteration', '0', '4d6 Stunden', '4d4 Quadratmeilen', '{"V","S","M"}',
   'Verändert das Wetter in einem großen Gebiet nach Wunsch des Zauberers.'),
  ('Todesfinger (Magier)', 6, 'wizard', 'necromancy', '30 Fuß', 'Sofort', '1 Kreatur', '{"V","S"}',
   'Tötet eine Kreatur sofort, wenn der Rettungswurf misslingt.'),
  ('Auflösung', 6, 'wizard', 'alteration', '5 Fuß/Stufe', 'Sofort', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Löst eine Kreatur oder ein Objekt vollständig auf. Kein Rettungswurf für Objekte.'),
  ('Gegenstand Verzaubern', 6, 'wizard', 'enchantment', 'Berührung', 'Speziell', '1 Objekt', '{"V","S","M"}',
   'Bereitet ein Objekt vor, um permanente Magie aufzunehmen.'),
  ('Böser Blick', 6, 'wizard', 'enchantment', '20 Fuß', '1 Runde/3 Stufen', '1 Kreatur', '{"V","S"}',
   'Blick verursacht Furcht, Krankheit, Schlaf oder Verlangsamung beim Ziel.'),
  ('Geas', 6, 'wizard', 'enchantment', '10 Fuß', 'Speziell', '1 Kreatur', '{"V"}',
   'Zwingt das Ziel, eine Aufgabe zu erfüllen. Missachtung verursacht Schwächung.'),
  ('Globus der Unverwundbarkeit', 6, 'wizard', 'abjuration', '0', '1 Runde/Stufe', '5 Fuß Radius', '{"V","S","M"}',
   'Kugel schützt den Zauberer vor Zaubern der Stufe 1-4.'),
  ('Schutzzauber', 6, 'wizard', 'abjuration', '0', '2 Stunden/Stufe', 'Speziell', '{"V","S","M"}',
   'Schützt einen Bereich mit vielfältigen magischen Fallen und Barrieren.'),
  ('Unsichtbarer Verfolger', 6, 'wizard', 'conjuration', '10 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Beschwört einen unsichtbaren Luftelementar, der einen Auftrag ausführt.'),
  ('Legendenkunde', 6, 'wizard', 'divination', '0', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Enthüllt Legenden und Informationen über eine Person, einen Ort oder Gegenstand.'),
  ('Massensuggestion', 6, 'wizard', 'enchantment', '10 Fuß/Stufe', 'Speziell', '1 Kreatur/Stufe', '{"V","S","M"}',
   'Wie Suggestion, wirkt aber auf mehrere Kreaturen gleichzeitig.'),
  ('Trugbild', 6, 'wizard', 'illusion', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Erzeugt eine illusorische Kopie des Zauberers und macht ihn unsichtbar.'),
  ('Monsterbeschwörung IV', 6, 'wizard', 'conjuration', 'Speziell', '5 Runden + 1 Runde/Stufe', '60 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d3 Monster mit 4 TW, die dem Zauberer gehorchen.'),
  ('Erde Bewegen', 6, 'wizard', 'alteration', '10 Fuß/Stufe', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Bewegt große Mengen Erde und formt das Gelände um.'),
  ('Otilukes Gefrierkugel', 6, 'wizard', 'invocation', '10 Fuß/Stufe', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Erzeugt verschiedene Kälteeffekte: Globus, Strahl oder Kälteexplosion.'),
  ('Permanente Illusion', 6, 'wizard', 'illusion', '10 Fuß/Stufe', 'Permanent', '20 Fuß Würfel + 10 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Erschafft eine dauerhafte Illusion mit Geräuschen und Bewegung.'),
  ('Programmierte Illusion', 6, 'wizard', 'illusion', '10 Fuß/Stufe', 'Speziell', '20 Fuß Würfel + 10 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Illusion, die durch ein bestimmtes Ereignis ausgelöst wird.'),
  ('Projektbild', 6, 'wizard', 'illusion', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Projiziert ein Bild des Zauberers, durch das er sehen und zaubern kann.'),
  ('Abstoßung', 6, 'wizard', 'abjuration', '10 Fuß/Stufe', '1 Runde/2 Stufen', '10 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Stößt bestimmte Kreaturen oder Objekte aus einem Bereich zurück.'),
  ('Stein zu Fleisch', 6, 'wizard', 'alteration', '10 Fuß/Stufe', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Verwandelt versteinerte Kreaturen zurück oder Stein in Fleisch.'),
  ('Tensers Transformation', 6, 'wizard', 'alteration', '0', '1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Verwandelt den Zauberer in einen Krieger mit verbesserten Kampfwerten.'),
  ('Wahres Sehen (Magier)', 6, 'wizard', 'divination', 'Berührung', '1 Runde/Stufe', '60 Fuß Blickfeld', '{"V","S","M"}',
   'Durchschaut alle Illusionen, Verwandlungen und sieht in Dunkelheit.'),
  ('Schleier', 6, 'wizard', 'illusion', '10 Fuß/Stufe', 'Speziell', 'Speziell', '{"V","S"}',
   'Verändert das Aussehen einer Gruppe von Kreaturen oder Objekten illusorisch.');

-- ── Wizard Level 7 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Verbannung', 7, 'wizard', 'abjuration', '20 Fuß', 'Sofort', '2 TW/Stufe', '{"V","S","M"}',
   'Verbannt außerplanare Kreaturen auf ihre Heimatebene.'),
  ('Untote Kontrollieren', 7, 'wizard', 'necromancy', '60 Fuß', '3d4 Runden + 1 Runde/Stufe', '1d6 Untote', '{"V","S","M"}',
   'Unterwirft Untote dem Willen des Zauberers.'),
  ('Verzögerter Feuerball', 7, 'wizard', 'invocation', '100 Fuß + 10 Fuß/Stufe', 'Speziell', '20 Fuß Radius', '{"V","S","M"}',
   'Feuerball mit Zeitzünder von 1-5 Runden. 1d6+1 Schaden pro Stufe (max 15d6+15).'),
  ('Drawmijs Sofortige Beschwörung', 7, 'wizard', 'conjuration', 'Unbegrenzt', 'Sofort', '1 Objekt', '{"V","S","M"}',
   'Teleportiert einen vorbereiteten Gegenstand sofort in die Hand des Zauberers.'),
  ('Duo-Dimension', 7, 'wizard', 'alteration', '0', '3 Runden + 1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Macht den Zauberer zweidimensional, nahezu unsichtbar von der Seite.'),
  ('Todesfinger', 7, 'wizard', 'necromancy', '60 Fuß', 'Sofort', '1 Kreatur', '{"V","S"}',
   'Tötet eine Kreatur sofort, wenn der Rettungswurf misslingt.'),
  ('Kraftkäfig', 7, 'wizard', 'invocation', '10 Fuß/2 Stufen', 'Speziell', '20 Fuß Würfel', '{"V","S","M"}',
   'Erzeugt einen unzerstörbaren Käfig aus Kraft, der Kreaturen gefangen hält.'),
  ('Begrenzter Wunsch', 7, 'wizard', 'conjuration', 'Unbegrenzt', 'Speziell', 'Speziell', '{"V"}',
   'Erfüllt einen begrenzten Wunsch. Schwächere Version von Wunsch.'),
  ('Massenunsuchtbarkeit', 7, 'wizard', 'illusion', '10 Fuß/Stufe', 'Speziell', '30 Fuß Radius', '{"V","S","M"}',
   'Macht alle Kreaturen in einem Bereich unsichtbar.'),
  ('Monsterbeschwörung V', 7, 'wizard', 'conjuration', 'Speziell', '6 Runden + 1 Runde/Stufe', '70 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d2 Monster mit 5 TW, die dem Zauberer gehorchen.'),
  ('Mordenkainens Prächtige Villa', 7, 'wizard', 'alteration', '10 Fuß', '1 Stunde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erschafft einen extradimensionalen Palast mit Dienern und Festmahl.'),
  ('Mordenkainens Schwert', 7, 'wizard', 'invocation', '30 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erschafft ein schwebendes Schwert, das wie ein Kämpfer der Stufe des Zauberers kämpft.'),
  ('Phasentür', 7, 'wizard', 'alteration', 'Berührung', '1 Benutzung/2 Stufen', 'Speziell', '{"V"}',
   'Erzeugt einen unsichtbaren Durchgang durch eine Wand für den Zauberer.'),
  ('Machtwort: Betäubung', 7, 'wizard', 'conjuration', '5 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V"}',
   'Betäubt eine Kreatur mit weniger als 90 TP sofort ohne Rettungswurf.'),
  ('Prismatischer Spray', 7, 'wizard', 'conjuration', '0', 'Sofort', '70 Fuß Kegel', '{"V","S"}',
   'Schießt 7 farbige Strahlen mit verschiedenen tödlichen Effekten.'),
  ('Schwerkraft Umkehren', 7, 'wizard', 'alteration', '5 Fuß/Stufe', '1 Runde/Stufe', '30 Fuß Quadrat', '{"V","S","M"}',
   'Kehrt die Schwerkraft in einem Bereich um — Kreaturen und Objekte fallen nach oben.'),
  ('Sequestrierung', 7, 'wizard', 'illusion', 'Berührung', '7 Tage + 1 Tag/Stufe', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Macht ein Objekt oder eine Kreatur unsichtbar und vor Ortung geschützt.'),
  ('Trugbild (Simulakrum)', 7, 'wizard', 'illusion', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Erschafft eine Kopie einer Kreatur aus Schnee und Eis mit Teilkräften.'),
  ('Zauberreflexion', 7, 'wizard', 'abjuration', '0', '3 Runden/Stufe', 'Zauberer', '{"V","S","M"}',
   'Reflektiert Zaubersprüche zurück auf den Angreifer.'),
  ('Statue', 7, 'wizard', 'alteration', 'Berührung', '1 Stunde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Verwandelt eine Kreatur in eine leblose Statue, die jederzeit zurückverwandelt werden kann.'),
  ('Teleportieren ohne Fehler', 7, 'wizard', 'alteration', 'Berührung', 'Sofort', 'Speziell', '{"V"}',
   'Wie Teleportieren, aber ohne Fehlerrisiko. Funktioniert immer perfekt.'),
  ('Verschwinden', 7, 'wizard', 'alteration', 'Berührung', 'Speziell', '1 Objekt', '{"V","S"}',
   'Teleportiert ein Objekt in einen extradimensionalen Raum.');

-- ── Wizard Level 8 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Antipathie-Sympathie', 8, 'wizard', 'enchantment', '30 Fuß', '2 Stunden/Stufe', 'Speziell', '{"V","S","M"}',
   'Macht einen Ort oder Gegenstand abstoßend oder anziehend für bestimmte Kreaturen.'),
  ('Bigbys Geballte Faust', 8, 'wizard', 'invocation', '5 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Riesige Krafthand greift an wie ein Kämpfer der Stufe des Zauberers. 1d6+11 Schaden.'),
  ('Bindung', 8, 'wizard', 'enchantment', '10 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Bindet eine außerplanare Kreatur in verschiedenen Formen der Gefangenschaft.'),
  ('Klon', 8, 'wizard', 'necromancy', 'Berührung', 'Permanent', '1 Klon', '{"V","S","M"}',
   'Erschafft einen Klon des Zauberers, der bei dessen Tod zum Leben erwacht.'),
  ('Forderung', 8, 'wizard', 'enchantment', 'Unbegrenzt', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Wie Sendung, aber mit einer Suggestion kombiniert.'),
  ('Glasstahl', 8, 'wizard', 'alteration', 'Berührung', 'Permanent', '1 Objekt', '{"V","S","M"}',
   'Macht Glas so hart wie Stahl, behält aber Transparenz.'),
  ('Brandwolke', 8, 'wizard', 'invocation', '30 Fuß', '1d6+4 Runden', '20x20x20 Fuß', '{"V","S","M"}',
   'Wolke aus glühendem Rauch verursacht jede Runde Schaden und bewegt sich.'),
  ('Massenbezauberung', 8, 'wizard', 'enchantment', '5 Fuß/Stufe', 'Speziell', 'Speziell', '{"V"}',
   'Wie Person Bezaubern, wirkt aber auf alle Kreaturen in einem Bereich.'),
  ('Irrgarten', 8, 'wizard', 'conjuration', '5 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Verbannt das Ziel in ein extradimensionales Labyrinth.'),
  ('Gedankenleere', 8, 'wizard', 'abjuration', '30 Fuß', '1 Tag', '1 Kreatur', '{"V","S"}',
   'Schützt vollständig vor ESP, Bezauberung und allen geistigen Angriffen.'),
  ('Monsterbeschwörung VI', 8, 'wizard', 'conjuration', 'Speziell', '7 Runden + 1 Runde/Stufe', '80 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d2 Monster mit 6 TW, die dem Zauberer gehorchen.'),
  ('Otilukes Telekinesekugel', 8, 'wizard', 'invocation', '10 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Wie Widerstandsfähige Kugel, kann aber vom Zauberer telekinetisch bewegt werden.'),
  ('Ottos Unwiderstehlicher Tanz', 8, 'wizard', 'enchantment', 'Berührung', '1d4+1 Runden', '1 Kreatur', '{"V"}',
   'Das Ziel beginnt unkontrolliert zu tanzen und kann nicht handeln.'),
  ('Permanenz', 8, 'wizard', 'alteration', 'Speziell', 'Permanent', 'Speziell', '{"V","S"}',
   'Macht bestimmte Zauber permanent. Kostet den Zauberer 1 Konstitutionspunkt.'),
  ('Beliebig Verwandeln', 8, 'wizard', 'alteration', '5 Fuß/Stufe', 'Permanent', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Verwandelt jede Kreatur oder jedes Objekt in beliebige andere Form.'),
  ('Machtwort: Blindheit', 8, 'wizard', 'conjuration', '5 Fuß/Stufe', 'Speziell', '1 Kreatur', '{"V"}',
   'Blendet eine Kreatur mit weniger als 100 TP sofort ohne Rettungswurf.'),
  ('Prismatische Wand', 8, 'wizard', 'conjuration', '10 Fuß', 'Speziell', 'Speziell', '{"V","S"}',
   'Erzeugt eine Wand aus 7 farbigen Schichten mit verschiedenen tödlichen Effekten.'),
  ('Abschirmung', 8, 'wizard', 'illusion', '0', '1 Stunde/Stufe', '30 Fuß Würfel/Stufe', '{"V","S"}',
   'Schützt einen Bereich vor Beobachtung und lässt ihn anders erscheinen.'),
  ('Sertens Zauberimmunität', 8, 'wizard', 'abjuration', 'Berührung', '1 Runde/Stufe', '1-4 Kreaturen', '{"V","S","M"}',
   'Macht Kreaturen immun gegen einen bestimmten Zauber.'),
  ('Versinken', 8, 'wizard', 'alteration', '10 Fuß/Stufe', 'Speziell', '1 Kreatur/Objekt', '{"V","S"}',
   'Lässt eine Kreatur im festen Boden versinken.'),
  ('Symbol (Magier)', 8, 'wizard', 'conjuration', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Zeichnet ein mächtiges Symbol mit verschiedenen verheerenden Effekten.'),
  ('Seele Fangen', 8, 'wizard', 'conjuration', '10 Fuß', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Fängt die Seele einer Kreatur in einem Edelstein gefangen.');

-- ── Wizard Level 9 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, school, range, duration, area_of_effect, components, description) values
  ('Astralzauber (Magier)', 9, 'wizard', 'alteration', 'Berührung', 'Speziell', 'Speziell', '{"V","S"}',
   'Der Zauberer und Begleiter reisen in Astralform auf die Astralebene.'),
  ('Bigbys Zerquetschende Hand', 9, 'wizard', 'invocation', '5 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Riesige Krafthand greift und zerquetscht das Ziel. 1d10+12 Schaden pro Runde.'),
  ('Kristallbrüchigkeit', 9, 'wizard', 'alteration', 'Berührung', 'Permanent', '1 Objekt', '{"V","S"}',
   'Macht Metall so brüchig wie Kristall, wodurch es bei Berührung zerbricht.'),
  ('Energieentzug', 9, 'wizard', 'necromancy', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Entzieht dem Ziel 2 Erfahrungsstufen bei Berührung.'),
  ('Voraussicht', 9, 'wizard', 'divination', '0', '2d4 Runden', 'Zauberer', '{"V","S","M"}',
   'Warnt den Zauberer vor unmittelbarer Gefahr und verleiht Überraschungsbonus.'),
  ('Tor (Magier)', 9, 'wizard', 'conjuration', '30 Fuß', 'Speziell', 'Speziell', '{"V","S"}',
   'Öffnet eine Pforte zu einer anderen Ebene und ruft möglicherweise mächtige Wesen.'),
  ('Gefangenschaft', 9, 'wizard', 'abjuration', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Verbannt eine Kreatur in eine winzige Kugel tief unter der Erde.'),
  ('Meteorschwarm', 9, 'wizard', 'invocation', '40 Fuß + 10 Fuß/Stufe', 'Sofort', 'Speziell', '{"V","S"}',
   'Vier große oder acht kleine Meteore mit verheerendem Feuerschaden.'),
  ('Monsterbeschwörung VII', 9, 'wizard', 'conjuration', 'Speziell', '8 Runden + 1 Runde/Stufe', '90 Fuß Radius', '{"V","S","M"}',
   'Beschwört 1d2 Monster mit 7 TW, die dem Zauberer gehorchen.'),
  ('Mordenkainens Disjunktion', 9, 'wizard', 'alteration', '0', 'Sofort', '30 Fuß Radius', '{"V"}',
   'Zerstört alle Magie in einem Bereich. Kann sogar Artefakte entzaubern.'),
  ('Machtwort: Tod', 9, 'wizard', 'conjuration', '5 Fuß/2 Stufen', 'Sofort', '1 Kreatur', '{"V"}',
   'Tötet eine Kreatur mit weniger als 120 TP sofort ohne Rettungswurf.'),
  ('Prismatische Kugel', 9, 'wizard', 'conjuration', '0', 'Speziell', '10 Fuß Radius', '{"V"}',
   'Kugel aus 7 farbigen Schichten mit verschiedenen tödlichen Effekten umgibt den Zauberer.'),
  ('Gestaltwandel', 9, 'wizard', 'alteration', '0', '1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Der Zauberer kann beliebig zwischen verschiedenen Kreaturformen wechseln.'),
  ('Beistand (Magier)', 9, 'wizard', 'alteration', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Erschafft einen Gegenstand, der den Besitzer zum Zauberer teleportiert.'),
  ('Zeitstillstand', 9, 'wizard', 'alteration', '0', '1d4+1 Runden', '15 Fuß Radius', '{"V"}',
   'Hält die Zeit für alle außer dem Zauberer an. Absolute Handlungsfreiheit.'),
  ('Zeitstasis', 9, 'wizard', 'alteration', 'Berührung', 'Permanent', '1 Kreatur/Objekt', '{"V","S","M"}',
   'Versetzt eine Kreatur oder ein Objekt in einen Zustand zeitlicher Stasis.'),
  ('Bizarr', 9, 'wizard', 'illusion', '30 Fuß', 'Speziell', '20 Fuß Radius', '{"V","S"}',
   'Erzeugt Illusionen der schlimmsten Ängste aller Kreaturen im Bereich.'),
  ('Wunsch', 9, 'wizard', 'conjuration', 'Unbegrenzt', 'Speziell', 'Speziell', '{"V"}',
   'Der mächtigste Zauber. Erfüllt nahezu jeden Wunsch, aber mit möglichen Nebeneffekten.');

-- ─── ADDITIONAL PRIEST SPELLS ────────────────────────────────────────────────

-- ── Priest Level 1 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Tierfreundschaft', 1, 'priest', 'animal', '10 Fuß', 'Permanent', '1 Tier', '{"V","S","M"}',
   'Gewinnt die Freundschaft eines Tieres, das zum treuen Begleiter wird.'),
  ('Zusammenwirken', 1, 'priest', 'all', 'Berührung', '1 Runde', 'Zauberer', '{"V","S"}',
   'Mehrere Priester verbinden ihre Kraft und verleihen einem Anführer Bonuszauber.'),
  ('Befehl', 1, 'priest', 'charm', '30 Fuß', '1 Runde', '1 Kreatur', '{"V"}',
   'Ein einzelnes Wort als Befehl, dem das Ziel für 1 Runde folgen muss.'),
  ('Wasser Erschaffen', 1, 'priest', 'elemental', '30 Fuß', 'Permanent', '27 Kubikfuß', '{"V","S","M"}',
   'Erschafft reines Trinkwasser. 4 Gallonen pro Zauberstufe.'),
  ('Böses Entdecken (Priester)', 1, 'priest', 'divination', '0', '1 Runde/Stufe + 1 Runde', '10x120 Fuß', '{"V","S"}',
   'Erkennt die Ausstrahlung von Bösem in einem Bereich.'),
  ('Magie Entdecken (Priester)', 1, 'priest', 'divination', '0', '1 Runde', '10x30 Fuß', '{"V","S"}',
   'Erkennt magische Auren in einem Bereich.'),
  ('Gift Entdecken', 1, 'priest', 'divination', '0', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erkennt Gift in einem Gegenstand oder einer Kreatur.'),
  ('Schlingen und Gruben Entdecken', 1, 'priest', 'divination', '0', '4 Runden', '10x40 Fuß', '{"V","S","M"}',
   'Erkennt natürliche und primitive Fallen im Umkreis.'),
  ('Hitze/Kälte Ertragen', 1, 'priest', 'protection', 'Berührung', '1 Stunde/Stufe', '1 Kreatur', '{"V","S"}',
   'Schützt vor extremen natürlichen Temperaturen.'),
  ('Verschlingen', 1, 'priest', 'plant', '80 Fuß', '1 Runde/Stufe', '40 Fuß Würfel', '{"V","S","M"}',
   'Pflanzen umschlingen Kreaturen im Bereich und halten sie fest.'),
  ('Feenfeuer', 1, 'priest', 'sun', '80 Fuß', '4 Runden/Stufe', 'Speziell', '{"V","S","M"}',
   'Umgibt Ziele mit einem leuchtenden Schein, der Unsichtbarkeit aufhebt.'),
  ('Unsichtbarkeit für Tiere', 1, 'priest', 'animal', 'Berührung', '1 Runde/Stufe + 1 Runde', 'Speziell', '{"V","S","M"}',
   'Das Ziel wird von Tieren nicht wahrgenommen.'),
  ('Tiere oder Pflanzen Orten', 1, 'priest', 'divination', '100 Fuß + 20 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Ortet die nächste Kreatur oder Pflanze einer bestimmten Art.'),
  ('Magischer Stein', 1, 'priest', 'combat', '40 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Verwandelt 3 Kieselsteine in magische Wurfgeschosse mit 1d4 Schaden.'),
  ('Spurloses Gehen', 1, 'priest', 'plant', 'Berührung', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Hinterlässt keine Spuren und kann nicht verfolgt werden.'),
  ('Nahrung und Wasser Reinigen', 1, 'priest', 'all', '30 Fuß', 'Permanent', '1 Fuß Würfel/Stufe', '{"V","S"}',
   'Entfernt Gift und Verderb aus Nahrung und Wasser.'),
  ('Angst Vertreiben', 1, 'priest', 'charm', 'Berührung', 'Speziell', '1 Kreatur/4 Stufen', '{"V","S"}',
   'Vertreibt Angst oder verleiht +4 auf Rettungswürfe gegen Furcht.'),
  ('Zuflucht', 1, 'priest', 'protection', '0', '2 Runden + 1 Runde/Stufe', 'Zauberer', '{"V","S","M"}',
   'Feinde können den Priester nicht direkt angreifen, solange er nicht angreift.'),
  ('Knüppelkeule', 1, 'priest', 'combat', 'Berührung', '4 Runden + 1 Runde/Stufe', '1 Knüppel', '{"V","S","M"}',
   'Verwandelt einen Knüppel in eine magische Waffe mit 2d4 Schaden.');

-- ── Priest Level 2 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Beistand', 2, 'priest', 'necromantic', 'Berührung', '1 Runde + 1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Verleiht +1 auf Angriff und RW sowie 1d8 temporäre Trefferpunkte.'),
  ('Weissagung', 2, 'priest', 'divination', '0', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Beantwortet eine Ja/Nein-Frage über eine zukünftige Handlung.'),
  ('Baumrinde', 2, 'priest', 'plant', 'Berührung', '4 Runden + 1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Senkt die Rüstungsklasse um 1 pro 4 Zauberstufen.'),
  ('Gesang', 2, 'priest', 'combat', '0', 'Speziell', '30 Fuß Radius', '{"V","S","M"}',
   'Monotoner Gesang gibt Verbündeten +1 und Feinden -1 auf Angriff, Schaden und RW.'),
  ('Person oder Säuger Bezaubern', 2, 'priest', 'animal', '80 Fuß', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Bezaubert eine Person oder ein Säugetier, das den Priester als Freund betrachtet.'),
  ('Verzauberung Erkennen', 2, 'priest', 'divination', '30 Fuß', '1 Runde', 'Speziell', '{"V","S"}',
   'Erkennt, ob eine Kreatur unter dem Einfluss von Bezauberungsmagie steht.'),
  ('Staubteufel', 2, 'priest', 'elemental', '30 Fuß', '2 Runden/Stufe', '5 Fuß Radius', '{"V","S"}',
   'Beschwört einen kleinen Staubwirbel, der angreift und blendet.'),
  ('Fesseln', 2, 'priest', 'charm', '60 Fuß', 'Speziell', 'Speziell', '{"V","S"}',
   'Fesselt die Aufmerksamkeit von Kreaturen, die dem Priester zuhören müssen.'),
  ('Fallen Finden', 2, 'priest', 'divination', '30 Fuß', '3 Runden', 'Speziell', '{"V","S"}',
   'Erkennt magische und mechanische Fallen im Blickfeld.'),
  ('Feuerfalle (Priester)', 2, 'priest', 'elemental', 'Berührung', 'Permanent', '1 Objekt', '{"V","S","M"}',
   'Verzaubert ein Objekt mit einer Feuerfalle. 1d4+Stufe Schaden beim Öffnen.'),
  ('Flammenklinge', 2, 'priest', 'elemental', '0', '4 Runden + 1 Runde/2 Stufen', 'Spezial', '{"V","S"}',
   'Erzeugt eine flammenförmige Klinge. 1d4+4 Feuerschaden.'),
  ('Gutbeeren', 2, 'priest', 'plant', 'Berührung', '1 Tag + 1 Tag/Stufe', '2d4 Beeren', '{"V","S","M"}',
   'Verwandelt Beeren in magische Nahrung, die je 1 TP heilt.'),
  ('Metall Erhitzen', 2, 'priest', 'elemental', '40 Fuß', '7 Runden', 'Speziell', '{"V","S","M"}',
   'Erhitzt Metall. Kreaturen in Metallrüstung erleiden steigenden Schaden.'),
  ('Person Festhalten (Priester)', 2, 'priest', 'charm', '120 Fuß', '2 Runden/Stufe', '1-4 Personen', '{"V","S","M"}',
   'Lähmt 1-4 humanoide Kreaturen, die sich nicht mehr bewegen können.'),
  ('Gesinnung Erkennen', 2, 'priest', 'divination', '10 Fuß', '1 Runde/Stufe', '1 Kreatur/Runde', '{"V","S"}',
   'Erkennt die Gesinnung einer Kreatur (gut/böse, chaotisch/gesetzestreu).'),
  ('Bote', 2, 'priest', 'animal', '20 Fuß/Stufe', 'Speziell', '1 Tier', '{"V","S"}',
   'Sendet ein kleines Tier als Boten zu einem bekannten Ort.'),
  ('Feuer-/Kälteresistenz', 2, 'priest', 'protection', 'Berührung', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Halbiert Feuer- oder Kälteschaden und gibt +3 auf entsprechende Rettungswürfe.'),
  ('Gift Verlangsamen', 2, 'priest', 'healing', 'Berührung', '1 Stunde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Verlangsamt die Wirkung von Gift und gibt Zeit zur Heilung.'),
  ('Schlange Bezaubern', 2, 'priest', 'animal', '30 Fuß', 'Speziell', 'Speziell', '{"V","S"}',
   'Bezaubert 1 Schlange pro Zauberstufe.'),
  ('Mit Tieren Sprechen', 2, 'priest', 'animal', '0', '2 Runden/Stufe', '1 Tier in 30 Fuß', '{"V","S"}',
   'Ermöglicht die Kommunikation mit einem Tier in einfacher Sprache.'),
  ('Geisthammer', 2, 'priest', 'combat', '10 Fuß/Stufe', '3 Runden + 1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erzeugt einen schwebenden Hammer aus Kraft, der wie eine magische Waffe angreift.'),
  ('Stolperfalle', 2, 'priest', 'plant', 'Berührung', '1 Runde/Stufe', '1 Pflanze', '{"V","S"}',
   'Verzaubert eine Pflanze, die vorbeigehende Kreaturen zu Fall bringt.'),
  ('Holz Verziehen', 2, 'priest', 'plant', '10 Fuß/Stufe', 'Permanent', 'Speziell', '{"V","S"}',
   'Verbiegt und verformt Holz — macht Türen unbrauchbar oder Pfeile nutzlos.'),
  ('Rückzug', 2, 'priest', 'protection', '0', 'Speziell', 'Zauberer', '{"V","S"}',
   'Der Priester zieht sich in Trance zurück und kann in Ruhe weitere Zauber vorbereiten.'),
  ('Lindwurmwache', 2, 'priest', 'guardian', '10 Fuß', '8 Stunden', '5 Fuß Radius', '{"V","S","M"}',
   'Erzeugt einen unsichtbaren Wächter, der eindringende Kreaturen paralysiert.');

-- ── Priest Level 3 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Untote Beleben (Priester)', 3, 'priest', 'necromantic', '10 Fuß', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Belebt Skelette oder Zombies aus Leichen. 1 Untoter pro Zauberstufe.'),
  ('Blitz Rufen', 3, 'priest', 'weather', '360 Fuß', '1 Runde/Stufe', '10 Fuß Radius', '{"V","S"}',
   'Ruft bei Gewitter Blitze herab. 2d8+Stufe Schaden pro Blitz.'),
  ('Dauerlicht (Priester)', 3, 'priest', 'sun', '120 Fuß', 'Permanent', '60 Fuß Radius', '{"V","S"}',
   'Erzeugt permanentes, helles Licht an einem Punkt oder Objekt.'),
  ('Nahrung und Wasser Erschaffen', 3, 'priest', 'creation', '10 Fuß', 'Speziell', '1 Fuß Würfel/Stufe', '{"V","S"}',
   'Erschafft Nahrung für 3 Personen/Stufe und Wasser für 1 Person/Stufe pro Tag.'),
  ('Blindheit oder Taubheit Heilen', 3, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Heilt magisch verursachte Blindheit oder Taubheit.'),
  ('Krankheit Heilen', 3, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Heilt alle Krankheiten, einschließlich magisch verursachter.'),
  ('Magie Bannen (Priester)', 3, 'priest', 'protection', '60 Fuß', 'Sofort', '30 Fuß Würfel', '{"V","S"}',
   'Hebt magische Effekte in einem Bereich auf.'),
  ('Scheintod', 3, 'priest', 'necromantic', 'Berührung', '1 Runde/Stufe + 1d4 Runden', 'Zauberer', '{"V","S"}',
   'Versetzt den Priester in einen todesähnlichen Zustand.'),
  ('Flammengang', 3, 'priest', 'elemental', 'Berührung', '1 Runde + 1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Schützt den Priester und Begleiter vor normalem Feuer und Hitze.'),
  ('Schutzglyphe', 3, 'priest', 'guardian', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Zeichnet eine magische Rune, die bei Berührung Schaden verursacht.'),
  ('Tier Festhalten', 3, 'priest', 'animal', '80 Fuß', '2 Runden/Stufe', '1-4 Tiere', '{"V","S"}',
   'Lähmt 1-4 Tiere, die sich nicht mehr bewegen können.'),
  ('Objekt Orten', 3, 'priest', 'divination', '60 Fuß + 10 Fuß/Stufe', '8 Stunden', 'Speziell', '{"V","S","M"}',
   'Ortet einen bekannten oder beschriebenen Gegenstand.'),
  ('Magisches Gewand', 3, 'priest', 'protection', '0', '5 Runden/Stufe', 'Zauberer', '{"V","S","M"}',
   'Verleiht dem Gewand des Priesters magischen Schutz wie eine Rüstung.'),
  ('In Stein Verschmelzen', 3, 'priest', 'elemental', 'Berührung', '8 Runden + 1d8 Runden', 'Zauberer', '{"V","S","M"}',
   'Der Priester verschmilzt mit Stein und ist darin unsichtbar und geschützt.'),
  ('Schutz vor negativer Ebene', 3, 'priest', 'protection', 'Berührung', '1 Runde/Stufe', '1 Kreatur', '{"V","S"}',
   'Schützt vor Energieentzug durch Untote und die negative Materieebene.'),
  ('Pflanzenwachstum (Priester)', 3, 'priest', 'plant', '160 Fuß', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Lässt Pflanzen in einem Bereich übermäßig wachsen und verwickeln.'),
  ('Feuerschutz', 3, 'priest', 'elemental', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Absorbiert Feuerschaden bis zu 12 TP pro Zauberstufe.'),
  ('Lähmung Aufheben', 3, 'priest', 'protection', '10 Fuß/Stufe', 'Permanent', '1d4 Kreaturen', '{"V","S"}',
   'Befreit 1d4 Kreaturen von Lähmung oder Verlangsamung.'),
  ('Falle', 3, 'priest', 'plant', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Erschafft eine magische Schlinge, die zuschnappt und festhält.'),
  ('Mit Toten Sprechen', 3, 'priest', 'divination', '1 Fuß', 'Speziell', '1 Leichnam', '{"V","S","M"}',
   'Stellt einem Leichnam Fragen, die er wahrheitsgemäß beantwortet.'),
  ('Dornenwuchs', 3, 'priest', 'plant', 'Berührung', '3d4 Runden + 1 Runde/Stufe', '10 Fuß Quadrat/Stufe', '{"V","S","M"}',
   'Lässt Dornen aus dem Boden wachsen, die 1d4 Schaden pro Bewegung verursachen.'),
  ('Stein Formen (Priester)', 3, 'priest', 'elemental', 'Berührung', 'Permanent', '1 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Formt Stein in jede gewünschte Form um.'),
  ('Insekten Beschwören', 3, 'priest', 'animal', '30 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Beschwört einen Schwarm Insekten, der Feinde angreift und plagt.'),
  ('Wasseratmung (Priester)', 3, 'priest', 'elemental', 'Berührung', '1 Stunde/Stufe', '1 Kreatur', '{"V","S"}',
   'Ermöglicht dem Ziel, unter Wasser zu atmen.'),
  ('Wasserwandeln', 3, 'priest', 'elemental', '0', '1 Runde/Stufe + 1 Runde', 'Speziell', '{"V","S","M"}',
   'Der Priester und Begleiter können auf der Wasseroberfläche gehen.');

-- ── Priest Level 4 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Abweisung', 4, 'priest', 'summoning', '10 Fuß', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Zwingt eine außerplanare Kreatur auf ihre Heimatebene zurück.'),
  ('Tierbeschwörung I', 4, 'priest', 'animal', '120 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört Tiere mit insgesamt 8 TW, die dem Priester gehorchen.'),
  ('Waldwesen Rufen', 4, 'priest', 'summoning', '100 Fuß + 10 Fuß/Stufe', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Ruft Waldwesen wie Dryaden, Pixies oder Zentauren herbei.'),
  ('Mantel der Tapferkeit', 4, 'priest', 'charm', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Macht das Ziel immun gegen Furchteffekte.'),
  ('Temperatur Kontrollieren 10 Fuß Radius', 4, 'priest', 'weather', '0', '4 Runden + 1 Runde/Stufe', '10 Fuß Radius', '{"V","S","M"}',
   'Ändert die Temperatur um bis zu 10 Grad pro Zauberstufe.'),
  ('Schwere Wunden Heilen (Verbessert)', 4, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Heilt 2d8+1 Trefferpunkte bei einer verletzten Kreatur.'),
  ('Lüge Erkennen', 4, 'priest', 'divination', '30 Fuß', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Erkennt, ob das Ziel lügt.'),
  ('Wahrsagung', 4, 'priest', 'divination', '0', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Gibt Auskunft über einen Ort, ein Objekt oder eine Kreatur mit höherer Genauigkeit.'),
  ('Freie Aktion', 4, 'priest', 'charm', 'Berührung', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Macht immun gegen Lähmung, Netz und Verlangsamung. Ermöglicht freie Unterwasserbewegung.'),
  ('Rieseninsekt', 4, 'priest', 'animal', 'Berührung', 'Speziell', '1-6 Insekten', '{"V","S","M"}',
   'Verwandelt normale Insekten in Rieseninsekten mit erhöhten TW.'),
  ('Halluzinatorischer Wald', 4, 'priest', 'plant', '80 Fuß', 'Permanent', '40 Fuß Quadrat/Stufe', '{"V","S"}',
   'Erzeugt die Illusion eines Waldes, der Kreaturen täuscht.'),
  ('Mit Zauberkraft Erfüllen', 4, 'priest', 'all', 'Berührung', 'Speziell', '1 Person', '{"V","S","M"}',
   'Verleiht einem Nicht-Priester die Fähigkeit, bestimmte Priesterzauber zu wirken.'),
  ('Wasser Senken', 4, 'priest', 'elemental', '120 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Senkt den Wasserspiegel in einem Bereich.'),
  ('Gift Neutralisieren', 4, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur/Objekt', '{"V","S"}',
   'Neutralisiert jedes Gift in einer Kreatur oder einem Gegenstand.'),
  ('Feuer Erzeugen', 4, 'priest', 'elemental', '40 Fuß', '1 Runde', 'Speziell', '{"V","S","M"}',
   'Erzeugt ein Feuer in einem Bereich oder entzündet brennbare Materialien.'),
  ('Schutz vor Bösem 10 Fuß Radius (Priester)', 4, 'priest', 'protection', 'Berührung', '1 Runde/Stufe', '10 Fuß Radius', '{"V","S","M"}',
   'Wie Schutz vor Bösem, aber schützt alle Kreaturen im 10-Fuß-Radius.'),
  ('Blitzschutz', 4, 'priest', 'protection', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S"}',
   'Absorbiert Blitzschaden bis zu 12 TP pro Zauberstufe.'),
  ('Spiegelbecken', 4, 'priest', 'divination', '10 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Ermöglicht Fernbeobachtung über ein stilles Gewässer wie durch eine Kristallkugel.'),
  ('Insekten Abwehren', 4, 'priest', 'animal', '0', '1 Runde/Stufe', '10 Fuß Radius', '{"V","S","M"}',
   'Hält normale und riesige Insekten fern.'),
  ('Mit Pflanzen Sprechen', 4, 'priest', 'plant', '0', '1 Runde/Stufe', '30 Fuß Radius', '{"V","S","M"}',
   'Ermöglicht die Kommunikation mit Pflanzen.'),
  ('Zauberimmunität', 4, 'priest', 'protection', 'Berührung', '1 Runde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Macht das Ziel immun gegen einen bestimmten Zauber.'),
  ('Stöcke zu Schlangen', 4, 'priest', 'plant', '30 Fuß', '2 Runden/Stufe', '1d4+Stufe Stöcke', '{"V","S","M"}',
   'Verwandelt Stöcke in Schlangen, die den Priester beschützen.'),
  ('Sprachen (Priester)', 4, 'priest', 'divination', '0', '1 Runde/Stufe', '60 Fuß Radius', '{"V","S"}',
   'Ermöglicht die Kommunikation in jeder gesprochenen Sprache.');

-- ── Priest Level 5 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Luftwandeln', 5, 'priest', 'elemental', 'Berührung', '1 Stunde/Stufe', '1 Kreatur', '{"V","S","M"}',
   'Ermöglicht dem Ziel, auf Luft zu wandeln wie auf festem Boden.'),
  ('Tierwachstum', 5, 'priest', 'animal', '80 Fuß', '1 Runde/Stufe', '1-8 Tiere', '{"V","S","M"}',
   'Verdoppelt die Größe und Kampfkraft von bis zu 8 Tieren.'),
  ('Tierbeschwörung II', 5, 'priest', 'animal', '180 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört Tiere mit insgesamt 12 TW, die dem Priester gehorchen.'),
  ('Buße', 5, 'priest', 'all', 'Berührung', 'Permanent', '1 Person', '{"V","S","M"}',
   'Ermöglicht einem reuigen Charakter die Rückkehr zu seiner Gesinnung und Klasse.'),
  ('Kommunion', 5, 'priest', 'divination', '0', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Kontaktiert die Gottheit und stellt 1 Ja/Nein-Frage pro Stufe.'),
  ('Kommunion mit der Natur', 5, 'priest', 'divination', '0', 'Speziell', '1 Meile/Stufe Radius', '{"V","S"}',
   'Gibt dem Priester umfassende Kenntnis über die umgebende Natur.'),
  ('Winde Kontrollieren', 5, 'priest', 'weather', '0', '1 Runde/Stufe', '40 Fuß/Stufe Radius', '{"V","S","M"}',
   'Kontrolliert Windstärke und -richtung in einem großen Bereich.'),
  ('Kritische Wunden Heilen', 5, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Heilt 3d8+3 Trefferpunkte bei einer verletzten Kreatur.'),
  ('Böses Bannen', 5, 'priest', 'protection', 'Berührung', '1 Runde/Stufe', 'Zauberer', '{"V","S"}',
   'Schützt vor bösen Kreaturen und kann Bezauberung brechen.'),
  ('Flammenschlag', 5, 'priest', 'combat', '60 Fuß', 'Sofort', '5 Fuß Radius, 30 Fuß hoch', '{"V","S","M"}',
   'Göttliche Feuersäule verursacht 6d8 Schaden (halb Feuer, halb göttlich).'),
  ('Insektenplage', 5, 'priest', 'combat', '120 Fuß', '2 Runden/Stufe', '180 Fuß Würfel', '{"V","S","M"}',
   'Riesiger Insektenschwarm greift alle Kreaturen im Bereich an.'),
  ('Magischer Quell', 5, 'priest', 'divination', 'Berührung', '1 Stunde/Stufe', 'Speziell', '{"V","S","M"}',
   'Ein Weihwasserbecken funktioniert wie eine Kristallkugel.'),
  ('Mondstrahl', 5, 'priest', 'sun', '60 Fuß', '1 Runde/Stufe', '5 Fuß Radius', '{"V","S","M"}',
   'Strahl aus Mondlicht beleuchtet einen Bereich und schadet Untoten.'),
  ('Pflanzenpassage', 5, 'priest', 'plant', 'Berührung', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Der Priester kann sich von einer Pflanze zu einer anderen teleportieren.'),
  ('Ebenenreise', 5, 'priest', 'astral', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Transportiert den Priester und Begleiter auf eine andere Existenzebene.'),
  ('Quest', 5, 'priest', 'charm', '60 Fuß', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Zwingt das Ziel, eine bestimmte Aufgabe zu erfüllen. Missachtung schadet.'),
  ('Regenbogen', 5, 'priest', 'weather', '120 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Erzeugt einen Regenbogen mit verschiedenen magischen Effekten.'),
  ('Tote Erwecken', 5, 'priest', 'necromantic', '30 Fuß', 'Permanent', '1 Person', '{"V","S"}',
   'Erweckt einen Toten zum Leben. Der Empfänger verliert 1 Konstitutionspunkt.'),
  ('Stachelfelsen', 5, 'priest', 'elemental', '30 Fuß', '3d4 Runden + 1 Runde/Stufe', '10 Fuß Quadrat/Stufe', '{"V","S","M"}',
   'Verwandelt Steinboden in scharfe Stacheln, die 1d4 Schaden verursachen.'),
  ('Fels zu Schlamm (Priester)', 5, 'priest', 'elemental', '160 Fuß', 'Speziell', '20 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Verwandelt Fels in Schlamm oder umgekehrt.'),
  ('Wahres Sehen (Priester)', 5, 'priest', 'divination', 'Berührung', '1 Runde/Stufe', '60 Fuß Blickfeld', '{"V","S","M"}',
   'Durchschaut alle Illusionen, Verwandlungen und sieht in Dunkelheit.'),
  ('Feuerwand (Priester)', 5, 'priest', 'elemental', '80 Fuß', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Erzeugt eine Wand aus Feuer, die Schaden beim Durchqueren verursacht.');

-- ── Priest Level 6 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Luftdiener', 6, 'priest', 'summoning', '10 Fuß', '1 Tag/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört einen mächtigen Luftelementar, der einen Auftrag ausführt.'),
  ('Tierbeschwörung III', 6, 'priest', 'animal', '240 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört Tiere mit insgesamt 16 TW, die dem Priester gehorchen.'),
  ('Objekt Beleben', 6, 'priest', 'summoning', '30 Fuß', '1 Runde/Stufe', '1 Fuß Würfel/Stufe', '{"V","S"}',
   'Belebt leblose Objekte, die sich bewegen und kämpfen können.'),
  ('Anti-Tier-Hülle', 6, 'priest', 'animal', '0', '1 Runde/Stufe', '10 Fuß Radius', '{"V","S","M"}',
   'Erzeugt eine Barriere, die kein Tier durchdringen kann.'),
  ('Klingenbarriere', 6, 'priest', 'guardian', '30 Fuß', '3 Runden/Stufe', '60 Fuß lang', '{"V","S"}',
   'Wand aus wirbelnden Klingen verursacht 8d8 Schaden beim Durchqueren.'),
  ('Tiere Herbeirufen', 6, 'priest', 'animal', '30 Fuß', '2 Runden/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört 1 oder mehrere Tiere, die für den Priester kämpfen.'),
  ('Feuerelementar Beschwören', 6, 'priest', 'elemental', '80 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört einen Feuerelementar mit 8, 12 oder 16 TW.'),
  ('Weg Finden', 6, 'priest', 'divination', 'Berührung', '1 Stunde/Stufe', 'Speziell', '{"V","S","M"}',
   'Zeigt den kürzesten, sichersten Weg zu einem bekannten Ziel.'),
  ('Feuersamen', 6, 'priest', 'elemental', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Verwandelt Eicheln oder Beeren in explosive Geschosse.'),
  ('Bann', 6, 'priest', 'protection', '30 Fuß', 'Permanent', '60 Fuß Würfel', '{"V","S","M"}',
   'Schützt einen Bereich dauerhaft vor magischem Zugang und Teleportation.'),
  ('Heilung', 6, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Heilt alle Trefferpunkte bis auf 1d4 und heilt Krankheit und Blindheit.'),
  ('Heldenmahl', 6, 'priest', 'creation', '10 Fuß', '1 Stunde', 'Speziell', '{"V","S","M"}',
   'Erschafft ein Festmahl, das Krankheiten heilt und Boni verleiht.'),
  ('Lebenseiche', 6, 'priest', 'plant', 'Berührung', 'Permanent', '1 Eiche', '{"V","S","M"}',
   'Verwandelt eine Eiche in einen treuen Wächter, der auf Befehl kämpft.'),
  ('Wasser Teilen', 6, 'priest', 'elemental', '20 Fuß/Stufe', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Teilt eine Wasserfläche und schafft einen trockenen Durchgang.'),
  ('Mit Monstern Sprechen', 6, 'priest', 'divination', '30 Fuß', '1 Runde/Stufe', '1 Kreatur', '{"V","S"}',
   'Ermöglicht die Kommunikation mit jeder Kreatur, die eine Sprache versteht.'),
  ('Stein Erzählt', 6, 'priest', 'elemental', 'Berührung', '1 Runde/Stufe', 'Speziell', '{"V","S","M"}',
   'Stein erzählt dem Priester, was in seiner Nähe geschehen ist.'),
  ('Pflanzenreise', 6, 'priest', 'plant', 'Berührung', 'Speziell', 'Zauberer', '{"V","S","M"}',
   'Teleportiert durch Pflanzen über beliebige Entfernungen.'),
  ('Holz Wenden', 6, 'priest', 'plant', '0', '1 Runde/Stufe', '120 Fuß Kegel', '{"V","S"}',
   'Stößt alle Holzobjekte aus einem Bereich weg.'),
  ('Dornenwand', 6, 'priest', 'plant', '80 Fuß', '1 Runde/Stufe', '10 Fuß Würfel/Stufe', '{"V","S"}',
   'Erzeugt eine dichte Wand aus Dornenranken, die Schaden verursacht.'),
  ('Wetter Beschwören', 6, 'priest', 'weather', '0', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Beschwört ein bestimmtes Wetter in der Umgebung.'),
  ('Worte der Rückkehr', 6, 'priest', 'summoning', '0', 'Sofort', 'Zauberer', '{"V"}',
   'Teleportiert den Priester sofort zu seinem Heiligtum zurück.');

-- ── Priest Level 7 ──────────────────────────────────────────────────────────

insert into public.spells (name, level, spell_type, sphere, range, duration, area_of_effect, components, description) values
  ('Stein Beleben', 7, 'priest', 'elemental', '40 Fuß', '1 Runde/Stufe', '2 Fuß Würfel/Stufe', '{"V","S","M"}',
   'Belebt Stein, der sich bewegt und kämpft.'),
  ('Astralzauber (Priester)', 7, 'priest', 'astral', 'Berührung', 'Speziell', 'Speziell', '{"V","S"}',
   'Der Priester und Begleiter reisen in Astralform auf die Astralebene.'),
  ('Stabwandlung', 7, 'priest', 'plant', 'Berührung', 'Permanent', '1 Stab', '{"V","S","M"}',
   'Verwandelt einen speziellen Stab in einen Treant-ähnlichen Wächter.'),
  ('Chariot von Sustarre', 7, 'priest', 'elemental', '10 Fuß', '12 Stunden', 'Speziell', '{"V","S","M"}',
   'Erschafft einen flammenden Wagen, der durch die Luft fliegen kann.'),
  ('Verwirrung (Priester)', 7, 'priest', 'charm', '80 Fuß', '1 Runde/Stufe', '20 Fuß Radius', '{"V","S","M"}',
   'Verwirrt Kreaturen, die zufällig handeln.'),
  ('Erdelementar Beschwören', 7, 'priest', 'elemental', '80 Fuß', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört einen Erdelementar mit 8, 12 oder 16 TW.'),
  ('Wetter Kontrollieren (Priester)', 7, 'priest', 'weather', '0', '4d12 Stunden', '4d4 Quadratmeilen', '{"V","S","M"}',
   'Verändert das Wetter in einem großen Gebiet nach Wunsch des Priesters.'),
  ('Kriechender Tod', 7, 'priest', 'animal', '0', '1 Runde/Stufe', 'Speziell', '{"V","S"}',
   'Beschwört Schwärme von Insekten, Spinnen und Schlangen, die alles verschlingen.'),
  ('Erdbeben', 7, 'priest', 'elemental', '120 Fuß', '1 Runde', '5 Fuß Durchmesser/Stufe', '{"V","S","M"}',
   'Verursacht ein verheerendes Erdbeben, das Gebäude zum Einsturz bringt.'),
  ('Forderung (Priester)', 7, 'priest', 'charm', '10 Fuß', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Zwingt eine außerplanare Kreatur zu einem Dienst gegen Gegenleistung.'),
  ('Feuersturm', 7, 'priest', 'elemental', '160 Fuß', 'Sofort', '2 Fuß Würfel/Stufe', '{"V","S"}',
   'Riesiger Feuersturm verursacht 2d8+Stufe Schaden in einem großen Bereich.'),
  ('Tor (Priester)', 7, 'priest', 'summoning', '30 Fuß', 'Speziell', 'Speziell', '{"V","S"}',
   'Öffnet eine Pforte zu einer anderen Ebene und ruft möglicherweise mächtige Wesen.'),
  ('Heiliges Wort', 7, 'priest', 'combat', '0', 'Sofort', '30 Fuß Radius', '{"V"}',
   'Göttliches Wort verbannt, tötet, lähmt oder betäubt böse Kreaturen je nach TW.'),
  ('Regeneration', 7, 'priest', 'healing', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S","M"}',
   'Lässt verlorene Gliedmaßen nachwachsen und heilt schwere Verletzungen.'),
  ('Reinkarnation', 7, 'priest', 'necromantic', 'Berührung', 'Permanent', '1 Person', '{"V","S"}',
   'Gibt einem Toten einen neuen Körper — die Rasse wird zufällig bestimmt.'),
  ('Wiederherstellung', 7, 'priest', 'necromantic', 'Berührung', 'Permanent', '1 Kreatur', '{"V","S"}',
   'Stellt verlorene Erfahrungsstufen oder Fähigkeitspunkte wieder her.'),
  ('Auferstehung', 7, 'priest', 'necromantic', 'Berührung', 'Permanent', '1 Person', '{"V","S","M"}',
   'Erweckt einen Toten vollständig zum Leben, selbst wenn nur Knochen übrig sind.'),
  ('Beistand (Priester)', 7, 'priest', 'summoning', 'Berührung', 'Speziell', '1 Kreatur', '{"V","S","M"}',
   'Erschafft einen Gegenstand, der den Besitzer zum Priester teleportiert.'),
  ('Sonnenstrahl', 7, 'priest', 'sun', '10 Fuß/Stufe', 'Sofort', '5 Fuß Radius', '{"V","S","M"}',
   'Gebündelter Sonnenstrahl verursacht enormen Schaden bei Untoten und blendet andere.'),
  ('Symbol (Priester)', 7, 'priest', 'guardian', 'Berührung', 'Speziell', 'Speziell', '{"V","S","M"}',
   'Zeichnet ein heiliges Symbol mit verschiedenen göttlichen Effekten.'),
  ('Metall zu Holz', 7, 'priest', 'elemental', '80 Fuß', 'Permanent', 'Speziell', '{"V","S","M"}',
   'Verwandelt Metallobjekte in Holz — zerstört Waffen und Rüstungen.'),
  ('Windwandeln', 7, 'priest', 'elemental', 'Berührung', '1 Stunde/Stufe', 'Speziell', '{"V","S","M"}',
   'Verwandelt den Priester und Begleiter in eine gasförmige Wolke, die fliegen kann.');
