-- ═══════════════════════════════════════════════════════════════════════════════
-- PR 4: PHB General Equipment Seed Data
-- ═══════════════════════════════════════════════════════════════════════════════

insert into public.general_items (name, name_en, weight, cost_gp, category) values
  ('Rucksack', 'Backpack', 2, 2, 'container'),
  ('Schlafsack', 'Bedroll', 5, 0.2, 'camping'),
  ('Gürtelbeutel (groß)', 'Belt Pouch (large)', 1, 1, 'container'),
  ('Gürtelbeutel (klein)', 'Belt Pouch (small)', 0.5, 0.7, 'container'),
  ('Kerze', 'Candle', 0, 0.01, 'light'),
  ('Kette (10 Fuß)', 'Chain (10 ft)', 3, 0.3, 'equipment'),
  ('Kreide', 'Chalk', 0, 0.01, 'equipment'),
  ('Feuerstein & Stahl', 'Flint & Steel', 0, 0.5, 'equipment'),
  ('Enterhaken', 'Grappling Hook', 4, 0.8, 'equipment'),
  ('Heiliges Symbol', 'Holy Symbol', 0, 25, 'religious'),
  ('Weihwasser (Fläschchen)', 'Holy Water (vial)', 0, 25, 'religious'),
  ('Tinte (Fläschchen)', 'Ink (vial)', 0, 8, 'writing'),
  ('Laterne (Blende)', 'Lantern (hooded)', 2, 7, 'light'),
  ('Laterne (Stier)', 'Lantern (bullseye)', 3, 12, 'light'),
  ('Spiegel (klein, Stahl)', 'Mirror (small, steel)', 0.5, 10, 'equipment'),
  ('Ölflasche', 'Oil Flask', 1, 0.06, 'light'),
  ('Pergament (Blatt)', 'Parchment (sheet)', 0, 0.2, 'writing'),
  ('Eisenrationen (1 Woche)', 'Iron Rations (1 week)', 7.5, 5, 'food'),
  ('Standardrationen (1 Woche)', 'Standard Rations (1 week)', 20, 3, 'food'),
  ('Seil, Hanf (50 Fuß)', 'Rope, Hemp (50 ft)', 20, 1, 'equipment'),
  ('Seil, Seide (50 Fuß)', 'Rope, Silk (50 ft)', 8, 10, 'equipment'),
  ('Sack (groß)', 'Sack (large)', 0.5, 0.02, 'container'),
  ('Sack (klein)', 'Sack (small)', 0.5, 0.05, 'container'),
  ('Siegelwachs', 'Sealing Wax', 0, 1, 'writing'),
  ('Nähnadel', 'Sewing Needle', 0, 0.5, 'equipment'),
  ('Signalpfeife', 'Signal Whistle', 0, 0.8, 'equipment'),
  ('Siegelring', 'Signet Ring', 0, 5, 'equipment'),
  ('Zauberbuch (leer)', 'Spellbook (blank)', 3, 15, 'writing'),
  ('Stachelkette (10 Fuß)', 'Spike, Iron (10)', 2.5, 0.1, 'equipment'),
  ('Zelt (klein)', 'Tent (small)', 10, 5, 'camping'),
  ('Zelt (groß)', 'Tent (large)', 20, 25, 'camping'),
  ('Zunderbüchse', 'Tinderbox', 0, 1, 'equipment'),
  ('Fackel', 'Torch', 1, 0.01, 'light'),
  ('Wasserschlauch', 'Waterskin', 1, 0.8, 'food'),
  ('Whetstone', 'Whetstone', 0, 0.02, 'equipment'),
  ('Weinschlauch', 'Wineskin', 1, 0.8, 'food'),
  ('Dietrich-Set', 'Thieves Tools', 1, 30, 'equipment'),
  ('Heiler-Set', 'Healer Kit', 3, 10, 'equipment'),
  ('Kletterhaken (10)', 'Pitons (10)', 2.5, 0.1, 'equipment'),
  ('Sattel & Zaumzeug', 'Saddle & Bridle', 25, 10, 'equipment');
